In [8]:
import numpy as np

In [9]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [10]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
array = np.zeros(10)
print(array.nbytes)

80


In [12]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [13]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [16]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


In [18]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.26210307 0.45889052 0.3534158 ]
  [0.6677565  0.19925511 0.80734052]
  [0.58918511 0.235309   0.59004471]]

 [[0.06961116 0.69718295 0.96169393]
  [0.05803441 0.00394157 0.56256019]
  [0.9550903  0.5000221  0.12170873]]

 [[0.31656622 0.15854171 0.38962659]
  [0.76025149 0.25447109 0.60225292]
  [0.94453848 0.64613478 0.95322776]]]


In [20]:
array_10x10 = np.random.random((10, 10))
min_value = np.min(array_10x10)
max_value = np.max(array_10x10)
print("Min:", min_value)
print("Max:", max_value)

Min: 0.0035799372520195494
Max: 0.9991100542016982


In [21]:

random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Mean:", mean_value)

Mean: 0.5680966449656102


In [22]:
size = 5  # Example size
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
existing_array = np.array([[1, 2], [3, 4]])
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [24]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [25]:
matrix_5x5 = np.diag([1, 2, 3, 4], k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(index)

(1, 5, 4)


In [28]:
checkerboard = np.tile([[1, 0], [0, 1]], (4, 4))
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [29]:
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized_matrix)

[[0.23570571 0.44382824 0.05907211 0.50081025 0.96593758]
 [1.         0.29278192 0.95382025 0.64146731 0.07185654]
 [0.55849166 0.5403365  0.5072574  0.17221862 0.42387838]
 [0.54971382 0.55027373 0.51144716 0.13948502 0.90528582]
 [0.37022547 0.26788241 0.82052336 0.50732764 0.        ]]


In [30]:
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [31]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print(product_matrix)

[[0.53895425 0.72468852]
 [0.9596184  0.88076269]
 [0.48782621 0.34762827]
 [0.57691068 0.52341279]
 [0.68361312 0.67812575]]


In [32]:
array = np.array([1, 4, 5, 7, 8, 9])
array[(array > 3) & (array < 8)] *= -1
print(array)

[ 1 -4 -5 -7  8  9]


In [33]:
# Author: Jake VanderPlas
print(sum(range(5), -1))

9


In [34]:
from numpy import *
print(sum(range(5), -1))

10


In [35]:
import numpy as np
Z = np.array([1, 2, 3])

print(Z**Z)       # Legal
print(2 << Z >> 2)  # Legal
print(Z < -Z)     # Legal
print(1j * Z)     # Legal
print(Z / 1 / 1) # Legal
print(Z < Z > Z) # Not legal

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Windows\Temp\ipykernel_9256\3728859435.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Windows\Temp\ipykernel_9256\3728859435.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Windows\Temp\ipykernel_9256\3728859435.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [ ]:
array = np.array([1.1, -1.1, 2.5, -2.5])
rounded_array = np.copysign(np.ceil(np.abs(array)), array)
print(rounded_array)

[ 2. -2.  3. -3.]


In [ ]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([3, 4, 5, 6])
common_values = np.intersect1d(array1, array2)
print(common_values)

[3 4]


In [ ]:
import numpy as np
import warnings

warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)


In [ ]:
import numpy as np

result = np.sqrt(-1) == np.emath.sqrt(-1)
print(result)

False


C:\Windows\Temp\ipykernel_9256\355266385.py:3: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(-1) == np.emath.sqrt(-1)


In [ ]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-08-18
Today: 2024-08-19
Tomorrow: 2024-08-20
