In [69]:
import tensorflow as tf

In [70]:
vector = tf.constant([1, 2, 3, 4, 5])
scalar = tf.constant(12)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [71]:
print("Shape:", tensor.shape)
print("Rank:", tf.rank(tensor))
print("Size:", tf.size(tensor))

Shape: (2, 2, 2)
Rank: tf.Tensor(3, shape=(), dtype=int32)
Size: tf.Tensor(8, shape=(), dtype=int32)


In [72]:
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1)

print(tensor1)
print(tensor2)

tf.Tensor(
[[0.5977851  0.02821028 0.87537444 ... 0.6576158  0.5796678  0.47277486]
 [0.2937026  0.34492588 0.9924984  ... 0.81169426 0.10104966 0.5576545 ]
 [0.30859947 0.95862603 0.8638469  ... 0.3370067  0.19616437 0.21365845]
 [0.29783857 0.68725586 0.54860806 ... 0.6980138  0.07340884 0.33079064]
 [0.48657453 0.98446393 0.68710554 ... 0.92826176 0.38746965 0.43784738]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.16782379 0.49902987 0.04408586 ... 0.3874477  0.66583264 0.97059023]
 [0.9523357  0.7723013  0.5110016  ... 0.05636883 0.8309939  0.3230604 ]
 [0.23419356 0.44497716 0.96185255 ... 0.02379107 0.7866638  0.46771538]
 [0.05962455 0.95817506 0.5242876  ... 0.96040547 0.19959009 0.5484474 ]
 [0.07783127 0.5947844  0.32937753 ... 0.7959354  0.73814    0.32504773]], shape=(5, 300), dtype=float32)


In [73]:
matmulResult = tf.matmul(tensor1, tf.transpose(tensor2))

print(matmulResult.shape)

(5, 5)


In [74]:
dotProduct = tf.tensordot(tensor1, tensor2, axes=[[1], [1]])

print(dotProduct.shape)

(5, 5)


In [75]:
imageTensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1)

print(imageTensor)

tf.Tensor(
[[[0.8588691  0.7792021  0.8323431 ]
  [0.759292   0.4021994  0.97028077]
  [0.801347   0.4245875  0.13003671]
  ...
  [0.26552534 0.359506   0.2139144 ]
  [0.45254922 0.23710978 0.72003746]
  [0.8426589  0.70554376 0.14245737]]

 [[0.7008821  0.4989928  0.45232415]
  [0.53101385 0.3452878  0.9478489 ]
  [0.980523   0.7900213  0.5024284 ]
  ...
  [0.77581275 0.19941461 0.10924447]
  [0.8884597  0.06972384 0.89683187]
  [0.83557034 0.6580287  0.78507674]]

 [[0.6126945  0.12011683 0.38150454]
  [0.25528467 0.84006727 0.9951246 ]
  [0.03522325 0.6135378  0.810073  ]
  ...
  [0.99927664 0.00335789 0.9891437 ]
  [0.3141234  0.69884205 0.7701497 ]
  [0.9258944  0.76325595 0.2558    ]]

 ...

 [[0.39689863 0.48394394 0.27857876]
  [0.924327   0.35160577 0.50312424]
  [0.976493   0.8695028  0.01176596]
  ...
  [0.6697041  0.81021297 0.61060464]
  [0.8203894  0.60039556 0.05826879]
  [0.87806344 0.3674115  0.5660616 ]]

 [[0.04831016 0.978662   0.9766269 ]
  [0.29547322 0.9543694  0

In [76]:
minVal = tf.reduce_min(imageTensor)
maxVal = tf.reduce_max(imageTensor)

print(minVal)
print(maxVal)

tf.Tensor(4.053116e-06, shape=(), dtype=float32)
tf.Tensor(0.99999475, shape=(), dtype=float32)


In [77]:
tensor3 = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1)
squeezedTensor = tf.squeeze(tensor3)

print(tensor3)
print(squeezedTensor)


tf.Tensor(
[[[[0.884727   0.9610405  0.5806905 ]
   [0.5970231  0.0705111  0.80104315]
   [0.92452693 0.5214201  0.5831586 ]
   ...
   [0.06188297 0.26149464 0.2805717 ]
   [0.50191736 0.93315375 0.91463196]
   [0.5752126  0.28300142 0.6908574 ]]

  [[0.03701389 0.1442455  0.09311712]
   [0.5351001  0.8161423  0.819227  ]
   [0.15324664 0.55710196 0.56621265]
   ...
   [0.43181658 0.8088988  0.08489096]
   [0.543437   0.38165712 0.93400097]
   [0.26812422 0.5904355  0.93375313]]

  [[0.3350681  0.53355396 0.5041039 ]
   [0.724638   0.70832276 0.99985397]
   [0.70928    0.8328918  0.67792165]
   ...
   [0.41971767 0.02334309 0.87089694]
   [0.07619619 0.8528248  0.69755435]
   [0.89444435 0.15585506 0.99240685]]

  ...

  [[0.7260461  0.7391646  0.5717485 ]
   [0.22708893 0.17967224 0.6543819 ]
   [0.46233022 0.27118158 0.8595686 ]
   ...
   [0.35450327 0.37411463 0.6538521 ]
   [0.5411775  0.7071476  0.5248792 ]
   [0.56866264 0.77302265 0.72824347]]

  [[0.85611725 0.522395   0.812189

In [78]:
tensor10 = tf.constant([10, 40, 5, 3, 15, 7, 25, 8, 81, 12])
maxIndex = tf.argmax(tensor10)

print(tensor10)
print(maxIndex)

tf.Tensor([10 40  5  3 15  7 25  8 81 12], shape=(10,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int64)


In [79]:
oneHotEncoded = tf.one_hot(tensor10, depth=26)

print(oneHotEncoded)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]], shape=(10, 26), dtype=float32)
